### ISSUE TITLE
No more connections allowed (max_client_conn)

### ISSUE THREAD

**Issue by klobastov** [kndndrj/nvim-dbee#152]
I  think dbbe should close connection after each sql request or use once connection

![image](https://github.com/user-attachments/assets/55996eec-e5b9-4d87-aa08-dcfac4c896cf)
`docker exec -it -u root db_pgbouncer_1 psql -p 6432 -U postgres pgbouncer -c "show clients"`

**docker-compose.yml**
```
version: "3.9"

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres # define credentials
      POSTGRES_PASSWORD: example # define credentials
      POSTGRES_DB: postgres # define database
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  pgbouncer:
    image: bitnami/pgbouncer
    restart: always
    environment:
      POSTGRESQL_PORT: 5432
      POSTGRESQL_HOST: db
      POSTGRESQL_USERNAME: postgres # define credentials
      POSTGRESQL_PASSWORD: example # define credentials
      PGBOUNCER_DATABASE: development
      PGBOUNCER_AUTH_TYPE: trust
      PGBOUNCER_POOL_MODE: transaction
      PGBOUNCER_STATS_USERS: postgres,developer
      PGBOUNCER_USERLIST_FILE: /bitnami/userlist.txt
    volumes:
      - ./userlist.txt:/bitnami/userlist.txt
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 5555:6432 # PgBouncer port
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost"]
  adminer:
    image: adminer
    restart: always
    links:
      - db:db
    ports:
      - 8080:8080
```

**userlist.txt**
```
"developer" "example"
```

**docker-entrypoint-initdb.d/init-user-db.sh**
```
#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER developer WITH PASSWORD 'example';
	CREATE DATABASE development;
	GRANT ALL PRIVILEGES ON DATABASE development TO developer;
	ALTER DATABASE development OWNER TO developer;
	GRANT USAGE, CREATE ON SCHEMA public TO developer;
	GRANT ALL PRIVILEGES ON TABLESPACE tsname TO developer;
EOSQL
```
